name: primeraChamba

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows
    steps:
      - name: RevisionRepo
        run: se esta ejecutando el entorno

      - name: AnalisisRepo
        run: se esta analizando el repositorio

ls -la

